# SITE CONFIGURATION
baseurl: ""
url: "https://forkit.info"
title: "Fork It"
tagline: "Bitcoin Forks<br>Upcoming & Past"

defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:permalink
      published: true
      author: "/u/Karlvonbahnhof"

ad:
  bitfinex: '<a rel="nofollow" target="_blank" href="https://www.bitfinex.com/?refcode=5egV78YtlC"><img src="https://gallery.mailchimp.com/b5cca524e997c8e12f8ad51e1/images/d928b3bc-d245-4039-bdb0-e668b0372114.jpg"></a><br>'
  ledger: '<a rel="nofollow" target="_blank" href="https://www.ledgerwallet.com/r/e274"><img alt="Ledger Wallet protects your bitcoins" src="/ads/ledger.gif"></a><br>'
